GET https://localhost:8443/users/Maks


###

POST https://localhost:8443/users
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@example.com",
    "password": "password",
    "role": "admin"
}

####
POST https://localhost:8443/login
Content-Type: application/json

{
    "name": "Admin",
    "password": "password"
}

####
POST https://localhost:8443/users/login
Content-Type: application/json

{
    "name": "Maks",
    "password": "password"
}

####
PATCH https://localhost:8443/users/Maks
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODJiYTA3NjI1Y2ZlMWZiNDMwMGJkZSIsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJBZG1pbiIsImlhdCI6MTczNjc5NjU1MSwiZXhwIjoxNzM2ODAwMTUxfQ.ghuh0-6JceNsDIaunR3lwrZRORnTwGlKsVr7TDaEPs0"
Content-Type: application/json

{
    "name": "Marek"
}

####
GET https://localhost:8443/library/common

####
GET https://localhost:8443/users/Admin/decks/Deck1
